### ISSUE TITLE
ドローンとの衝突イベント対応する

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-unity-drone-model#6]
# 対応項目

1. ドローンモデルのコライダーの単純化
2. 衝突イベントの実装
3. https://github.com/toppers/hakoniwa-ros2pdu/issues/7
4. 衝突イベントをPDUデータとして書き込む

**Comment by tmori** [comment]
# ドローンモデルのコライダーの単純化

BoxColliderは、ルートオブジェクトの DroneAvatorにつける
ベーススケール：X=1.0, Y=0.1, Z=1.0
スケールサイズ：X=2.5, Y=4, Z=2.5

![スクリーンショット 2024-01-07 10 05 58](https://github.com/toppers/hakoniwa-unity-drone-model/assets/164193/5872cf75-51f9-48df-acf1-1866ce8443eb)

![スクリーンショット 2024-01-07 10 06 30](https://github.com/toppers/hakoniwa-unity-drone-model/assets/164193/efbc7dee-860f-45a3-a807-6c4259a11361)

![スクリーンショット 2024-01-07 10 06 47](https://github.com/toppers/hakoniwa-unity-drone-model/assets/164193/9f667f9c-aa71-4e61-9c90-047115c418c3)

**Comment by tmori** [comment]
# 衝突イベントの実装

いくつかトラブったのでメモ

自分のオブジェクトがOnColllisionEnterで反応するための条件
* 自分のオブジェクトのCollider の IsTriggerはFalseでなければならない
  * IsTriggerがTrueの場合は、OnTriggerEnterが発火するが、これは今回の目的とは違うのでよくない
* 対抗側のオブジェクトにRigidbodyがアタッチされていないといけない
* 対抗側のオブジェクトにRigidbodyにIsKinematicが設定されていると反応しない


自分の方：
![スクリーンショット 2024-01-07 13 13 27](https://github.com/toppers/hakoniwa-unity-drone-model/assets/164193/f4343dca-e04e-4555-a7d6-400cfb03e761)

相手側：

![スクリーンショット 2024-01-07 13 16 48](https://github.com/toppers/hakoniwa-unity-drone-model/assets/164193/9b1fe74e-0865-4a8a-8e9b-efbf1204435e)
9bc4096f6)

**Comment by tmori** [comment]
# まずは前方方向の障害物に真正面からぶつかった時のデータを採取

座標系は、ROS座標系。
正面は東の方向。
10mホバリング状態。

こんな感じ。

![image](https://github.com/toppers/hakoniwa-unity-drone-model/assets/164193/f7a652ba-8e4d-4213-8f54-949ed4097c50)

ぶつかった時の衝突データ

* Number of contact points: 4
* Relative Velocity: (0.00, 0.02, 0.00)
* Contact point 0: Position - (1.03, -7.50, 10.13)
* Contact point 1: Position - (-1.47, -7.45, 9.87)
* Contact point 2: Position - (1.03, -7.47, 9.73)
* Contact point 3: Position - (-1.47, -7.47, 10.12)

サイズが大きいのは、Unity上で再現しているモデルのサイズが、2.5m x 2.5m のサイズのため。

# 障害物の位置とスケール

Unity座標系の位置　　： (10, 7.3, 0)
Unity座標系のスケール： (5, 15, 5)

ROS座標系の位置　　： (0, -10, 7.3)
ROS座標系のスケール： (5, 5, 15)

ROS座標系での障害物の位置の中心に対して、
2.5m四方が境界なので、
Y軸方向の衝突位置が-7.5mなのは納得した。
X軸方向の衝突位置は、ばらつきがあるのはなぜだろう。

1.03と-1.47


衝突検出が機体の端っこだとすると、
1.25と-1.25が上限になると思ったが、
0.2mほどずれている。

おそらく、真東に移動させきれなかったと思えば納得いく。

**Comment by tmori** [comment]
# 自分のオブジェクトの端っこが衝突ポイントなんだ！

<img width="546" alt="スクリーンショット 2024-01-07 14 45 04" src="https://github.com/toppers/hakoniwa-unity-drone-model/assets/164193/d4759ad0-df3e-4cd7-b65c-7790953a2d4b">

**Comment by tmori** [comment]
この修正を追加で実施した

https://github.com/toppers/hakoniwa-unity-drone-model/issues/7

**Comment by kenjihiranabe** [comment]
よかった。想定通りです。僕の方の計算は、
実際にはどちらかの端が先にあたるので、そこで角度持って跳ね返すようにしてます。
(もっと凝るならトルクも与えるのだけど、まあ、最初は単純に)

**Comment by tmori** [comment]
球のコライダーはめり込むので、やっぱり違和感あった。
ので、元に戻します。
